# -- CREATE DATABAS
CREATE DATABASE IF NOT EXISTS MSG_APP;

# SELECT DB
USE MSG_APP;

# -- CREATE USERLIST TABLE
CREATE TABLE userlist (
  UID int NOT NULL,
  USER_NAME varchar(100) DEFAULT NULL,
  USER_PASSWORD varchar(100) DEFAULT NULL,
  MOBILE_NO bigint DEFAULT NULL,
  PRIMARY KEY (UID),
  UNIQUE KEY UID (UID)
) ;

# -- CREATE MSG TABLE
CREATE TABLE msgs (
  MID int NOT NULL,
  MSG_TXT varchar(5000) DEFAULT NULL,
  FROM_ID int DEFAULT NULL,
  TO_ID int DEFAULT NULL,
  MSG_TIME date DEFAULT NULL,
  SID int DEFAULT NULL,
  PRIMARY KEY (MID),
  CONSTRAINT msgs_ibfk_1 FOREIGN KEY (SID) REFERENCES userlist (UID)
) ;

# -- INSERTING FIRST RECORD
INSERT INTO USERLIST VALUES(1, 'Admin', 'Admin@123', '1234567890');
INSERT INTO MSGS VALUES(1, 'Hi', 1, 1, '9999-12-31', 1);